# Generated by Django 3.2.6 on 2021-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_sp', models.FloatField()),
                ('insulin', models.FloatField()),
                ('meals', models.FloatField()),
                ('glucose', models.CharField(max_length=30)),
            ],
        ),
    ]
