# Generated by Django 4.1.7 on 2023-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='exeint',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='predresults',
            name='namemeals',
            field=models.CharField(default='No meal', max_length=255),
        ),
    ]
