# Generated by Django 4.1.7 on 2023-02-25 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predresults_exeint_predresults_namemeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='datetimepicker1',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
