# Generated by Django 4.1.7 on 2023-02-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_predresults_datetimepicker1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='datetimepicker1',
        ),
    ]
